[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solady/=lib/solady/src/",
    "@solady/=lib/solady/src/"
]

[fmt]
single_line_statement_blocks = "multi"
sort_imports = true
wrap_comments = true
bracket_spacing = true
line_length = 100
multiline_func_header = "params_first"
contract_new_lines = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
